const actionTypes = {
  START_DESKTOP_APP: '__START_DESKTOP_APP',
  START_MOBILE_APP: '__START_MOBILE_APP',
  CHANGE_HISTORY: '__CHANGE_HISTORY',

  FETCH_ACCOUNTS: '__FETCH_ACCOUNTS',
  CREATE_ACCOUNT: '__CREATE_ACCOUNT',
  FAIL_TO_CREATE_ACCOUNT: '__FAIL_TO_CREATE_ACCOUNT',
  UPDATE_ACCOUNT: '__UPDATE_ACCOUNT',
  FAIL_TO_UPDATE_ACCOUNT: '__FAIL_TO_UPDATE_ACCOUNT',
  DELETE_ACCOUNT: '__DELETE_ACCOUNT',
  FAIL_TO_DELETE_ACCOUNT: '__FAIL_TO_DELETE_ACCOUNT',

  FETCH_USER_STATUS: '__FETCH_USER_STATUS',
  FETCH_USER_SETTING: '__FETCH_USER_SETTING',
};

export default actionTypes;
