default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: hold_development

test:
  <<: *default
  database: hold_test

production:
  <<: *default
  database: hold_production
  username: hold
  password: <%= ENV['HOLD_DATABASE_PASSWORD'] %>
