default_twitter: &default_twitter
  twitter_api_key: <%= ENV["TWITTER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_SECRET"] %>

development:
  secret_key_base: cfbfc3c8636d7f1233d5590190c78a079a275e582d2e4d83f86bef6cdb00d203fcc2b9b157c4ab2e1ff39378b379bf6f290b515f7f2ad8adb140f1da578ed0e8
  <<: *default_twitter

test:
  secret_key_base: 38cb620ed920b74656c9677d476bacd589a6dcdafca62e246034e54c8514f57ca678267650deb5c4bea24219d600f3f0c939629b6ee20f57710ccf6925d6b6ab
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
